# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\countingtool.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CountingTool(object):
    def setupUi(self, CountingTool):
        CountingTool.setObjectName("CountingTool")
        CountingTool.resize(1422, 1126)
        self.centralWidget = QtWidgets.QWidget(CountingTool)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topPart = QtWidgets.QWidget(self.centralWidget)
        self.topPart.setObjectName("topPart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.topPart)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.winInput = QtWidgets.QLabel(self.topPart)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.winInput.setFont(font)
        self.winInput.setText("")
        self.winInput.setPixmap(QtGui.QPixmap(":/backgrounds/images/Input.png"))
        self.winInput.setObjectName("winInput")
        self.horizontalLayout_3.addWidget(self.winInput)
        self.line_4 = QtWidgets.QFrame(self.topPart)
        self.line_4.setMidLineWidth(10)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_3.addWidget(self.line_4)
        self.line_6 = QtWidgets.QFrame(self.topPart)
        self.line_6.setMidLineWidth(10)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_3.addWidget(self.line_6)
        self.winResult = QtWidgets.QLabel(self.topPart)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.winResult.setFont(font)
        self.winResult.setAutoFillBackground(False)
        self.winResult.setText("")
        self.winResult.setPixmap(QtGui.QPixmap(":/backgrounds/images/result.png"))
        self.winResult.setObjectName("winResult")
        self.horizontalLayout_3.addWidget(self.winResult)
        self.verticalLayout.addWidget(self.topPart)
        self.midPart = QtWidgets.QWidget(self.centralWidget)
        self.midPart.setObjectName("midPart")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.midPart)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_window = QtWidgets.QWidget(self.midPart)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.btn_window.setFont(font)
        self.btn_window.setObjectName("btn_window")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.btn_window)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.btn_window)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.widget_3 = QtWidgets.QWidget(self.btn_window)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnVideo = QtWidgets.QPushButton(self.widget_3)
        self.btnVideo.setObjectName("btnVideo")
        self.gridLayout.addWidget(self.btnVideo, 2, 1, 1, 1)
        self.btnImage = QtWidgets.QPushButton(self.widget_3)
        self.btnImage.setObjectName("btnImage")
        self.gridLayout.addWidget(self.btnImage, 2, 0, 1, 1)
        self.btnRun = QtWidgets.QPushButton(self.widget_3)
        self.btnRun.setObjectName("btnRun")
        self.gridLayout.addWidget(self.btnRun, 4, 0, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.widget_3)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 4, 1, 1, 1)
        self.btnCamera = QtWidgets.QPushButton(self.widget_3)
        self.btnCamera.setObjectName("btnCamera")
        self.gridLayout.addWidget(self.btnCamera, 2, 2, 1, 1)
        self.btnClear = QtWidgets.QPushButton(self.widget_3)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 4, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.horizontalLayout_2.addWidget(self.btn_window)
        self.line_3 = QtWidgets.QFrame(self.midPart)
        self.line_3.setMidLineWidth(10)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.widget_2 = QtWidgets.QWidget(self.midPart)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.winCountingResult = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.winCountingResult.setFont(font)
        self.winCountingResult.setObjectName("winCountingResult")
        self.verticalLayout_6.addWidget(self.winCountingResult)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.midPart)
        self.buttomPart = QtWidgets.QWidget(self.centralWidget)
        self.buttomPart.setObjectName("buttomPart")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttomPart)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bbox_window = QtWidgets.QWidget(self.buttomPart)
        self.bbox_window.setObjectName("bbox_window")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bbox_window)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.bbox_window)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.winDetection = QtWidgets.QLabel(self.bbox_window)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.winDetection.setFont(font)
        self.winDetection.setText("")
        self.winDetection.setPixmap(QtGui.QPixmap(":/backgrounds/images/Detection.png"))
        self.winDetection.setObjectName("winDetection")
        self.verticalLayout_3.addWidget(self.winDetection)
        self.horizontalLayout.addWidget(self.bbox_window)
        self.line = QtWidgets.QFrame(self.buttomPart)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.density_window = QtWidgets.QWidget(self.buttomPart)
        self.density_window.setObjectName("density_window")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.density_window)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.density_window)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.winDensity = QtWidgets.QLabel(self.density_window)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.winDensity.setFont(font)
        self.winDensity.setText("")
        self.winDensity.setPixmap(QtGui.QPixmap(":/backgrounds/images/Density.png"))
        self.winDensity.setObjectName("winDensity")
        self.verticalLayout_4.addWidget(self.winDensity)
        self.horizontalLayout.addWidget(self.density_window)
        self.widget = QtWidgets.QWidget(self.buttomPart)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.barScale = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barScale.sizePolicy().hasHeightForWidth())
        self.barScale.setSizePolicy(sizePolicy)
        self.barScale.setMinimumSize(QtCore.QSize(0, 0))
        self.barScale.setMaximum(50)
        self.barScale.setOrientation(QtCore.Qt.Vertical)
        self.barScale.setObjectName("barScale")
        self.verticalLayout_2.addWidget(self.barScale)
        self.textScale = QtWidgets.QTextBrowser(self.widget)
        self.textScale.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.textScale.sizePolicy().hasHeightForWidth())
        self.textScale.setSizePolicy(sizePolicy)
        self.textScale.setMaximumSize(QtCore.QSize(1000, 50))
        self.textScale.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textScale.setObjectName("textScale")
        self.verticalLayout_2.addWidget(self.textScale)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.widget)
        self.line_2 = QtWidgets.QFrame(self.buttomPart)
        self.line_2.setEnabled(True)
        self.line_2.setMidLineWidth(10)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.scalemap_window = QtWidgets.QWidget(self.buttomPart)
        self.scalemap_window.setObjectName("scalemap_window")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scalemap_window)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.scalemap_window)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.winScaleMap = QtWidgets.QLabel(self.scalemap_window)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.winScaleMap.setFont(font)
        self.winScaleMap.setText("")
        self.winScaleMap.setPixmap(QtGui.QPixmap(":/backgrounds/images/ScaleMap.png"))
        self.winScaleMap.setObjectName("winScaleMap")
        self.verticalLayout_5.addWidget(self.winScaleMap)
        self.horizontalLayout.addWidget(self.scalemap_window)
        self.verticalLayout.addWidget(self.buttomPart)
        CountingTool.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(CountingTool)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1422, 19))
        self.menuBar.setObjectName("menuBar")
        CountingTool.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(CountingTool)
        self.mainToolBar.setObjectName("mainToolBar")
        CountingTool.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(CountingTool)
        self.statusBar.setObjectName("statusBar")
        CountingTool.setStatusBar(self.statusBar)

        self.retranslateUi(CountingTool)
        QtCore.QMetaObject.connectSlotsByName(CountingTool)

    def retranslateUi(self, CountingTool):
        _translate = QtCore.QCoreApplication.translate
        CountingTool.setWindowTitle(_translate("CountingTool", "CountingTool"))
        self.label_5.setText(_translate("CountingTool", "Button"))
        self.btnVideo.setText(_translate("CountingTool", "Video"))
        self.btnImage.setText(_translate("CountingTool", "Image"))
        self.btnRun.setText(_translate("CountingTool", "Run"))
        self.btnStop.setText(_translate("CountingTool", "Stop"))
        self.btnCamera.setText(_translate("CountingTool", "Camera"))
        self.btnClear.setText(_translate("CountingTool", "Clear"))
        self.label_4.setText(_translate("CountingTool", "Message Window"))
        self.winCountingResult.setText(_translate("CountingTool", "当前人数"))
        self.label.setText(_translate("CountingTool", "bbox"))
        self.label_2.setText(_translate("CountingTool", "Density map"))
        self.label_3.setText(_translate("CountingTool", "Scale Map"))


import res_rc
